#defaults.pcm.rate_converter "samplerate_best"
defaults.pcm.rate_converter "speexrate_best"

pcm.dmixed {
    type dmix
    ipc_key 1027
    ipc_key_add_uid 0
    # mpd has audio group, tv/mzz are not
    ipc_perm 0660
    slave {
        pcm "hw:CARD=rk3588es8316,DEV=0"
        period_time 0
        period_size 1024
        buffer_size 8192
        rate 48000
    }
}

pcm.!default {
    type plug
    slave.pcm "dmixed"
    hint {
        show on
        description "ALSA Default card with mixer"
    }
}

ctl.!default {
    type hw
    card "rk3588es8316"
}
